[project]
name = "sentiment-analysis-using-naive-bayes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "nltk>=3.9.1",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
]
